[package]
name = "rust-cli-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_csv = "1.0"
tokio = { version = "1.0", features = ["full"] }
rayon = "1.5"
walkdir = "2.3"
inotify = "0.9"
